// horoscopeData.ts
export const horoscopeData = {
  activities: {
    juego: {
      predictions: [
        "tendrás una energía extraordinaria para jugar",
        "encontrarás un juguete favorito olvidado",
        "descubrirás un nuevo juego fascinante",
        "tu humano iniciará sesiones de juego especiales",
        "un juguete misterioso aparecerá en tu camino",
        "tendrás energía extra para perseguir todo lo que se mueva",
        "tus reflejos estarán más agudos que nunca",
        "encontrarás diversión en los lugares más inesperados",
        "te convertirás en el maestro de la caza del láser",
        "todos los juguetes parecerán nuevos para ti",
        "descubrirás el poder oculto de una simple pelota de papel",
        "te sorprenderás con las alturas que puedes alcanzar",
        "encontrarás el escondite perfecto para emboscar",
        "tu agilidad será digna de un atleta olímpico",
        "cada salto será más elegante que el anterior",
      ],
      contexts: [
        "durante la mañana",
        "en tu rincón favorito",
        "con otros amigos felinos",
        "cerca de la ventana",
        "con tu humano",
        "en el jardín",
        "en la sala",
        "después de una deliciosa comida",
        "mientras tu humano trabaja",
        "durante el atardecer",
        "cuando menos te lo esperes",
      ],
    },
    descanso: {
      predictions: [
        "encontrarás el lugar perfecto para una siesta",
        "tendrás sueños místicos reveladores",
        "descubrirás un nuevo rincón acogedor",
        "sentirás una paz extraordinaria",
        "encontrarás el lugar más cálido y cómodo para tus siestas",
        "tus sueños estarán llenos de atunes y ratoncitos",
        "descubrirás un nuevo rincón perfecto para descansar",
        "tendrás las siestas más reparadoras del mes",
        "tu ronroneo atraerá la tranquilidad",
        "una manta suave será tu mejor aliada",
        "el lugar más inesperado resultará ser el más cómodo",
        "tus sueños estarán llenos de aventuras épicas",
        "tu descanso inspirará envidia en otros felinos",
      ],
      contexts: [
        "bajo un rayo de sol",
        "en el sofá más cómodo",
        "junto a tu humano",
        "en tu cama favorita",
        "en la tarde",
        "después de jugar",
        "en tu lugar favorito",
        "mientras llueve afuera",
        "después de un largo día de juego",
        "en un rincón tranquilo",
      ],
    },
    comida: {
      predictions: [
        "te esperan delicias especiales",
        "tu paladar estará más refinado",
        "recibirás premios inesperados",
        "descubrirás nuevos sabores",
        "serás recompensado con un manjar especial",
        "tu plato estará más lleno de lo esperado",
        "un sabor exótico alegrará tu día",
        "tendrás una degustación digna de un chef",
        "descubrirás tu nuevo alimento favorito",
      ],
      contexts: [
        "durante la hora de la cena",
        "en tu plato favorito",
        "de manos de tu humano",
        "en la cocina",
        "mientras exploras la cocina",
        "junto a tu humano favorito",
        "en el momento más inesperado",
      ],
    },
    exploración: {
      predictions: [
        "descubrirás nuevos territorios",
        "encontrarás tesoros ocultos",
        "harás hallazgos misteriosos",
        "te aventurarás en lugares inexplorados",
        "tus instintos de cazador estarán al máximo",
        "un misterioso objeto móvil captará tu atención",
        "tu técnica de acecho será imparable",
        "descubrirás nuevas presas para acechar",
        "descubrirás un rincón inexplorado de tu territorio",
        "una aventura emocionante te espera cerca de casa",
        "tus bigotes te guiarán hacia algo interesante",
        "encontrarás un nuevo punto de observación",
        "una nueva ventana cambiará tu perspectiva",
        "hallarás un tesoro oculto bajo los muebles",
        "un aroma interesante te guiará a un lugar mágico",
        "tu curiosidad será recompensada con descubrimientos increíbles",
      ],
      contexts: [
        "en el jardín",
        "detrás de los muebles",
        "en los rincones más altos",
        "cerca de las ventanas",
        "en la noche",
        "durante el amanecer",
        "en los momentos más tranquilos",
        "mientras tu humano está distraído",
        "en el rincón más oscuro de la casa",
        "al perseguir un sonido intrigante",
      ],
    },
  },
  luckySpots: [
    "la ventana soleada",
    "el sofá más alto",
    "la cama de tu humano",
    "el rascador nuevo",
    "la caja misteriosa",
    "el alféizar de la ventana",
    "el jardín trasero",
    "la caja nueva",
    "el jardín",
    "la cocina",
    "la almohada más suave",
    "un rincón soleado en el piso",
    "el hueco de un mueble",
    "la manta de tu humano",
    "un armario que estará abierto justo a tiempo",
    "un zapato olvidado",
    "el estante más alto de la sala",
    "la sombra de un árbol en el jardín",
  ],
  compatibility: [
    "gatos siameses",
    "gatos persas",
    "gatos atigrados",
    "gatos negros",
    "gatos blancos",
    "gatos callejeros",
    "gatos mayores",
    "gatos dormilones",
    "gatitos juguetones",
    "gatitos curiosos",
    "gatos aventureros",
    "gatos tranquilos",
    "gatos peludos",
    "gatos pequeños",
    "gatos curiosos",
    "gatos que aman jugar",
    "gatos que adoran dormir todo el día",
  ],
  advice: [
    "observa el mundo desde diferentes alturas hoy",
    "comparte tus juguetes con otros felinos",
    "practica tu ronroneo sanador",
    "estírate más seguido durante el día",
    "toma el sol en diferentes lugares",
    "persigue tus sueños (y también ratones)",
    "mantén tus bigotes alerta",
    "cultiva tu curiosidad natural",
    "mantén tus bigotes alerta para nuevas oportunidades",
    "no dejes que un pepino te asuste hoy",
    "comparte tus golosinas con un amigo felino",
    "practica tu mejor maullido",
    "estírate bien antes de cada siesta",
    "mantén tu cola en alto",
    "confía en tus instintos felinos",
    "Muestra tu amor a tu humano favorito",
    "A veces, una siesta extra es la mejor decisión",
    "no temas mostrar tu personalidad",
    "escucha los susurros del viento y sigue tu instinto",
    "nunca subestimes el poder de un buen escondite",
    "el ronroneo puede curar cualquier cosa",
    "explora, incluso si ya crees conocer todo",
    "a veces, mirar fijamente a tu humano es la mejor estrategia",
    "hoy es un buen día para dejar caer cosas desde las alturas",
    "aprovecha cada oportunidad para relajarte bajo el sol",
    "recuerda: tú eres el verdadero dueño de la casa",
    "confía en tu sexto sentido para detectar el mejor lugar de descanso",
  ],
};
